INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('1', 'Hành chính - Thư ký');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('2', 'An ninh - Bảo vệ');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('3', 'Thiết kế - Sáng tạo nghệ thuật');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('4', 'Kiến trúc - Thiết kế nội ngoại thất');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('5', 'Khách sạn - Nhà hàng - Du lịch');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('6', 'Bán sỉ - Bán lẻ - Quản lý cửa hàng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('7', 'IT Phần cứng - Mạng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('8', 'IT Phần mềm');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('9', 'Sản xuất - Lắp ráp - Chế biến');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('10', 'Vận hành - Bảo trì - Bảo dưỡng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('11', 'Nông - Lâm - Ngư nghiệp');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('12', 'Marketing');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('13', 'Bán hàng - Kinh doanh');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('14', 'Thu mua - Kho Vận - Chuỗi cung ứng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('15', 'Xuất Nhập Khẩu');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('16', 'Vận Tải - Lái xe - Giao nhận');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('17', 'Kế toán');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('18', 'Tài chính - Đầu tư - Chứng Khoán');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('19', 'Ngân hàng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('20', 'Khai thác năng lượng - Khoáng sản - Địa chất');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('21', 'Y tế - Chăm sóc sức khỏe');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('22', 'Nhân sự');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('23', 'Bảo hiểm');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('24', 'Thông tin - Truyền thông - Quảng cáo');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('25', 'Luật - Pháp Lý - Tuân thủ');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('26', 'Kiểm toán');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('27', 'Quản lý dự án');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('28', 'Quản lý tiêu chuẩn và chất lượng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('29', 'Bất động sản');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('30', 'Chăm sóc khách hàng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('31', 'Xây dựng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('32', 'Giáo dục - Đào tạo');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('33', 'Phân tích - Thống kê dữ liệu');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('34', 'Khoa học - Kỹ thuật');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('35', 'Nghề nghiệp khác');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('36', 'An toàn lao động');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('37', 'Biên phiên dịch');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('38', 'Bưu chính viễn thông');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('39', 'Dầu khí');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('40', 'Dệt may - Da giày - Thời trang');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('41', 'Điện - Điện tử - Điện lạnh');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('42', 'Dược phẩm');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('43', 'Hóa học - Hóa sinh');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('44', 'Môi trường - Xử lý chất thải');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('45', 'Thực phẩm - Đồ uống');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('46', 'Chăn nuôi - Thú y');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('47', 'Cơ khí - Ô tô - Tự động hóa');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('48', 'Công nghệ thực phẩm - Dinh dưỡng');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('49', 'Lao động phổ thông');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('50', 'Phi chính phủ - Phi lợi nhuận');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('51', 'Truyền hình - Báo chí - Biên tập');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('52', 'Xuất bản - In ấn');
INSERT INTO `pbl3test`.`industry` (`INDUSTRY_ID`, `INDUSTRY_NAME`) VALUES ('53', 'Thực tập sinh');
